# Diese Variante läuft in einem Container, läuft aber nicht richtig sauber, da einzene Dateien beim Neustart von Containern zurück gesetzt werden.


# Ubuntu-18.04 für Mysql-5.7
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y && \
    apt-get install -y openjdk-11-jre-headless mariadb-server-10.6 ruby ranger systemctl
#    apt-get install -y openjdk-11-jre-headless mysql-server ruby ranger  # Ubuntu-18.04


COPY mo-installer /mo-installer
COPY ["2022-02-23_Mo_config_15420_5046577760.xml", "/mo-installer/"]

RUN echo "\n\
[mysqld]\n\
lower_case_table_names = 1\n\
" > /etc/mysql/mariadb.conf.d/case_insensitive.cnf
# RUN echo "\n\
# [mysqld]\n\
# lower_case_table_names = 1\n\
# " > /etc/mysql/mysql.conf.d/case_insensitive.cnf

RUN service mariadb start && \
echo "\
  CREATE DATABASE mo CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci; \
  CREATE USER 'mo'@'localhost' IDENTIFIED BY 'mopw'; \
  GRANT ALL PRIVILEGES ON *.* TO 'mo'@'localhost'; \
  FLUSH PRIVILEGES; \
" | mysql -h localhost


# RUN sed -i 's/MySQL 5.7/\*/g' /mo-installer/Setup/morequirements.xml

RUN service mariadb start && \
echo "1\n\
1\n\
1\n\
/mo-installer/2022-02-23_Mo_config_15420_5046577760.xml\n\
1\n\
2511\n\
80\n\
mailoptimizer\n\
mailoptimizer\n\
/\n\
n\n\
MySQL via JDBC\n\
jdbc:mysql://localhost:3306/mo?useSSL=false&serverTimezone=CET\n\
mo\n\
mopw\n\
1\n\
\n\
\n\
" | bash /mo-installer/Setup_MO_x32_x64.sh -c -Dinstall4j.keepLog=true -Dinstall4j.debug=true -Dinstall4j.alternativeLogfile=/mo-unattended.log

# COPY MO_Classic_Installation_Linux.prop /mo-installer/
# RUN service mariadb start && bash /mo-installer/Setup_MO_x32_x64.sh -q -console -varfile /mo-installer/MO_Classic_Installation_Linux.prop -Dinstall4j.keepLog=true -Dinstall4j.debug=true

RUN service mariadb start && \
    echo "\
      UPDATE mo.anwendungskonfiguration SET wert='DE' WHERE schluessel='user.str.conf.language'; \
    " | mysql -h localhost

RUN service mariadb start && \
    /bin/bash /opt/mailoptimizer/Software/Tomcat/bin/startup.sh && \
    sleep 40 && \
    /bin/bash /opt/mailoptimizer/Software/Tomcat/bin/shutdown.sh

COPY comcard-proxy-2019.crt /
RUN keytool -importcert -trustcacerts -keystore /opt/mailoptimizer/Software/Tomcat/conf/cacerts.jks -file /comcard-proxy-2019.crt -storepass changeit -alias comcard-2019 -no-prompt
RUN keytool -importcert -trustcacerts -keystore /opt/mailoptimizer/Software/Tomcat/conf/MoTrustStore.jks -file /comcard-proxy-2019.crt -storepass changeit -alias comcard-2019 -no-prompt
RUN keytool -importcert -trustcacerts -cacerts -file /comcard-proxy-2019.crt -storepass changeit -alias comcard-2019 -no-prompt

# Zum testen von pre-release Gems:
COPY mailoptimizer_server-*.gem /
RUN gem sources -a http://ccgems && \
    gem inst --no-doc mailoptimizer_server --verbose

EXPOSE 2511/tcp
EXPOSE 8765/tcp

VOLUME /opt/mailoptimizer/Kunden
VOLUME /opt/mailoptimizer/Software/Konfiguration
VOLUME /var/lib/mysql

ENV CATALINA_PID /opt/mailoptimizer/Software/Tomcat/tomcat.pid
ENV CATALINA_HOME /opt/mailoptimizer/Software/Tomcat
ENV CATALINA_BASE /opt/mailoptimizer/Software/Tomcat
ENV LANG=de_DE.UTF-8
ENV LANGUAGE=de

CMD service mariadb start && \
    (/bin/bash /opt/mailoptimizer/Software/Tomcat/bin/startup.sh &) && \
    mailoptimizer_server -s tcpserver://0.0.0.0 -v -d /opt/mailoptimizer/Kunden/15420
